columnSuffix: null
contentColumnType: string
fieldGroup: 82e9651c-cdbe-4765-8347-e523862e8fc0 # Common
handle: pageBuilder
instructions: ''
name: 'Page Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
