dateModified: 1648085703
email:
  fromEmail: fultonchain@gmail.com
  fromName: 'Craft Testing'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    01fb5d53-ea51-4102-9328-e22074af990f: 'Home Page' # Home Page
    2b6ea8d6-2ed9-4de7-b2d3-743a2bc01fef: 'Left Aligned' # Left Aligned
    2ecafbb1-21be-4677-8532-5a53fc0ed73c: 'Text (two column)' # Text (two column)
    4f53ccd8-02d6-4dfb-9af5-066766203a22: Caption # Caption
    5ce6d327-9f95-4eaa-a874-ba131d83e595: 'Code Block' # Code Block
    6c844d76-9e89-471a-9a4c-4aecb2870128: 'Code Block' # Code Block
    6f2a0dc6-56c7-4961-9ec2-345da8e1c4bd: 'Optimized Gallery Image' # Optimized Gallery Image
    8cf3f69b-e2c9-4aee-8ccd-07502688353b: Image # Image
    8d6f1019-1e9f-41ca-8b21-c587939c7123: Photos # Photos
    8d8c70a5-ca05-40de-9d25-0d7c4b4f24fd: Code # Code
    8f96e12f-89ce-4356-8d16-627a03ce664b: 'Gallery Matrix' # Gallery Matrix
    9c5019f2-58d3-4aed-92ac-d128ba7c2ebd: 'Image Heading' # Image Heading
    14eddc2b-911e-4699-805f-9da6bb4e2ed3: Default # Default
    016fab9a-3b2e-43aa-98ff-eec3b1a422b5: Photos # Photos
    33f0efdb-80d2-497f-b85f-28f29976c831: 'Image Right' # Image Right
    49d93205-bf01-4993-9476-5244792f13ab: 'Column Header Text' # Column Header Text
    65a187c0-9d8c-48be-b227-29909555488c: 'Image Text' # Image Text
    79d32bc9-6f45-45ba-aa62-1420e6aeacbc: 'Two columns' # Two columns
    82e9651c-cdbe-4765-8347-e523862e8fc0: Common # Common
    90db916c-859b-43b3-90b7-58741f542e8f: Image # Image
    96b74d21-8a42-4624-a0be-bb94e1033113: 'Main Menu' # Main Menu
    98c3b3fd-d591-4297-b458-611ab6bfa023: Gallery # Gallery
    440b1c6e-f595-4025-8642-ca8f4af12c8c: 'Photos Index' # Photos Index
    801d01c6-aa54-4d3a-8270-8d66b741bc84: Images # Images
    946ba5da-fba8-435d-9837-f219799e9b72: '640 Wide' # 640 Wide
    6342d4f9-ff1d-42b4-a3c9-4e5671993a45: 'Craft Testing' # Craft Testing
    96447b4d-438f-4e7d-ab79-2a591aeaa45a: 'Text (Markdown)' # Text (Markdown)
    281152d5-2276-41b8-9df1-9b333ba9aed1: Photos # Photos
    a00e2be9-15f2-408a-bbae-c18887e550b4: 'Image Heading' # Image Heading
    a8beaafe-7619-4c9e-b539-bef03612ef1c: 'Home Page' # Home Page
    a8e41503-5109-4d4f-be9d-ad9be3ee288b: 'Text Markdown' # Text Markdown
    bf4a1251-9e93-4e63-8309-a16809036706: 'Craft Boilerplate' # Craft Boilerplate
    c357f363-cd0d-42d3-97db-feee6d33a11a: 'Two Columns' # Two Columns
    d2a5ba19-a932-4f42-81be-b505cf4c47fa: 'Page Builder' # Page Builder
    d60ecc90-e9f9-4e49-95c0-36098e47e7d3: Pages # Pages
    d528e0c8-e295-451b-932e-41716e42ef5a: 'Gallery Title' # Gallery Title
    d740c045-6303-4f14-b7bf-cb99b1f5b957: 'Image Left' # Image Left
    d5703ed5-e82f-4f13-98a8-6f3ed4fe5647: 'Text Markdown' # Text Markdown
    daabfca9-958d-45f0-8de9-3df436ec424e: 'Gallery Images' # Gallery Images
    dbe9c138-db39-49c6-9d77-84462f2a4459: 'Image Left' # Image Left
    e36e5402-4515-4576-ab76-a3d44880b8e3: 'Image Right' # Image Right
    e982e30c-1eda-4358-b9ba-d345fae9f372: 'Optimized Page Image' # Optimized Page Image
    e94294e6-bfe6-4c49-a338-1ce3034f77b7: 'Image Text' # Image Text
    eac19060-9ecd-49b0-8f2b-1fe18da8ac14: 'Photos Index' # Photos Index
    eb571e57-a9ea-4e77-80c2-18bb0c53da9d: Text # Text
    fa97c374-d5c0-46c1-b3e0-6c7414de82f6: Default # Default
plugins:
  cheat-sheet:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  expanded-singles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-optimize:
    edition: standard
    enabled: true
    licenseKey: I6XXFP2SEY2AWTY645VCOXOS
    schemaVersion: 1.0.0
    settings:
      allowUpScaledImageVariants: false
      assetVolumeSubFolders: true
      autoSharpenScaledImages: true
      capSilhouetteSvgSize: false
      createColorPalette: true
      createPlaceholderSilhouettes: false
      imageTransformTypeSettings:
        __assoc__:
          -
            - nystudio107\imageoptimizeimgix\imagetransforms\ImgixImageTransform
            -
              __assoc__:
                -
                  - domain
                  - ''
                -
                  - apiKey
                  - ''
                -
                  - securityToken
                  - ''
                -
                  - unsharpMask
                  - '20'
          -
            - nystudio107\imageoptimizesharp\imagetransforms\SharpImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
          -
            - nystudio107\imageoptimizethumbor\imagetransforms\ThumborImageTransform
            -
              __assoc__:
                -
                  - baseUrl
                  - ''
                -
                  - securityKey
                  - ''
      lowerQualityRetinaImageVariants: true
      sharpenScaledImagePercentage: 50
      transformClass: nystudio107\imageoptimize\imagetransforms\CraftImageTransform
  matrixtoolbar:
    edition: standard
    enabled: true
    schemaVersion: 1.0.4
  navigation:
    edition: standard
    enabled: true
    licenseKey: X29ZS6S6L9FTVJBBLWSAC8EM
    schemaVersion: 1.0.21
  syntax-highlighter:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      copytoClipboardButton: '1'
      defaultLanguage: markup
      enableLineHighlight: ''
      enableLineNumbers: '1'
      maxHeight: '500'
      selectedLanguages:
        - markup
        - css
        - javascript
        - markdown
        - twig
      selectedTheme: prism-okaidia
      showLanguage: ''
system:
  edition: pro
  live: true
  name: 'Craft Testing'
  retryDuration: null
  schemaVersion: 3.7.33
  timeZone: America/New_York
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
