defaultPlacement: end
enableVersioning: true
handle: homePage
name: 'Home Page'
propagationMethod: all
siteSettings:
  bf4a1251-9e93-4e63-8309-a16809036706: # Craft Boilerplate
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
